CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL     VARCHAR(20) NOT NULL,
    LOGIN     VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    BIRTHDAY  DATE
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    USER_ID   INT REFERENCES USERS (USER_ID),
    FRIEND_ID INT REFERENCES USERS (USER_ID),
    PRIMARY KEY (USER_ID, FRIEND_ID)
);


CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID   INT PRIMARY KEY,
    MPA_NAME VARCHAR(20) NOT NULL
);


CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID      INT PRIMARY KEY AUTO_INCREMENT,
    FILM_NAME    VARCHAR(50)  NOT NULL,
    DESCRIPTION  VARCHAR(200) NOT NULL,
    RELEASE_DATE DATE,
    DURATION     INT,
    MPA_ID       INT REFERENCES MPA (MPA_ID)
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID   INT PRIMARY KEY,
    GENRE_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    FILM_ID  INT REFERENCES FILMS (FILM_ID),
    GENRE_ID INT REFERENCES GENRES (GENRE_ID),
    PRIMARY KEY (FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS LIKES
(
    FILM_ID INT REFERENCES FILMS (FILM_ID),
    USER_ID INT REFERENCES USERS (USER_ID),
    PRIMARY KEY (FILM_ID, USER_ID)
);

//merge into GENRES (GENRE_ID, GENRE_NAME)
    values ( 1, 'Комедия' ),
           (2, 'Драма'),
           (3, 'Мультфильм'),
           (4, 'Триллер'),
           (5, 'Документальный'),
           (6, 'Боевик');

//merge into MPA (MPA_ID, MPA_NAME)
    values ( 1,  'G'),
           (2,'PG'),
           (3, 'PG-13'),
           (4, 'R'),
           (5, 'NC-17');

//insert into USERS (EMAIL, LOGIN, USER_NAME, BIRTHDAY) VALUES ( 'yandex@ya.ru', 'dolar', 'Nik', '1985-10-10' );

//insert into FILMS (FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ( 'New film', 'New film about friends', '1999-04-30', '120', '3' );
